name: form_field_validator
description: A straightforward flutter form field validator that provides common validation options.
version: 1.0.1
homepage: https://github.com/Milad-Akarie/form_field_validator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.18.1"


dev_dependencies:
  flutter_test:
    sdk: flutter
